# The configuration for the builder is in YAML format. You can use
# https://www.yamllint.com/ to make sure that your configuration
# file is correctly formatted.

# First we need to define the source files to build. Please list
# all sources in the same family. These are expected to be in the
# sources/ directory, so all paths should be relative to that
# directory.
sources:
  - Firjar.glyphs
axisOrder:
  - wdth
  - wght
# You don't have to supply the family name, but builds are slightly
# faster if you do.
familyName: "Firjar"

# Next you can supply alternative paths for where you want the
# binaries to live. But we'd recommend you stick to the defaults
# especially if you are planning to upload your font to Google Fonts.

outputDir: ../fonts
vfDir: $outputDir/variable
ttDir: $outputDir/ttf
otDir: $outputDir/otf
woffDir: $outputDir/webfonts

# The following entries, which are either "true" or "false"
# determine which targets to build. We turn off OTFs for this demo.

#buildVariable: true
# buildStatic: true
buildTTF: true
buildOTF: false
# buildSmallCap: false

# The next flags control autohinting.
autohintTTF: false
autohintOTF: false
# ttfaUseScript: false  # Set this to true if your font is not Latin

# The "fix" operation can optionally fix some problems which
# are better dealt with in the font sources. Set this to true if you
# want gftools-fix to automatically fix source problems.
# includeSourceFixes: false

# These options give fine-grained control over how fontmake builds
# the fonts.
# EraseOpenCornersFilter: false
# flattenComponents: true
# decomposeTransformedComponents: true
# checkCompatibility: true
# overlaps: booleanOperations
# expandFeaturesToInstances: false
# reverseOutlineDirection: true
# removeOutlineOverlaps: true
# extraFontmakeArgs: ""
# extraVariableFontmakeArgs: ""
# extraStaticFontmakeArgs: ""
# glyphData: GlyphData.xml

# This control how STAT tables are generated. The STAT table is
# specified here as a list of axis names, tags and values. You
# can either map a list to each output VF, or provide a single
# list which is used for all VFs. Note that the build will fail
# if you specify a dictionary which does not contain an entry
# for each VF file built.
stat:
  Firjar[wdth,wght].ttf:
  - name: Width
    tag: wdth
    values:
    - name: Condensed
      value: 75
    - name: SemiCondensed
      value: 87.5
    - name: Normal
      value: 100
    - name: SemiExpanded
      value: 112.5
    - name: Expanded
      value: 125
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100
    - name: ExtraLight
      value: 200
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
    - name: Black
      value: 900
instances:
  Firjar[wdth,wght].ttf:
  - familyName: "Firjar Condensed"
    styleName: "Thin"
    coordinates:
      wdth: 75
      wght: 100
  - familyName: "Firjar Condensed"
    styleName: "ExtraLight"
    coordinates:
      wdth: 75
      wght: 200
  - familyName: "Firjar Condensed"
    styleName: "Light"
  - coordinates:
      wdth: 75
      wght: 300
  - familyName: "Firjar Condensed"
    styleName: "Regular"
  - coordinates:
      wdth: 75
      wght: 400
  - familyName: "Firjar Condensed"
    styleName: "SemiBold"
  - coordinates:
      wdth: 75
      wght: 600
  - familyName: "Firjar Condensed"
    styleName: "Bold"
  - coordinates:
      wdth: 75
      wght: 700
  - familyName: "Firjar Condensed"
    styleName: "ExtraBold"
  - coordinates:
      wdth: 75
      wght: 800
  - familyName: "Firjar Condensed"
    styleName: "Black"
  - coordinates:
      wdth: 75
      wght: 900
  - familyName: "Firjar SemiCondensed"
    styleName: "Thin"
  - coordinates:
      wdth: 87.5
      wght: 100
  - familyName: "Firjar SemiCondensed"
    styleName: "ExtraLight"
  - coordinates:
      wdth: 87.5
      wght: 200
  - familyName: "Firjar SemiCondensed"
    styleName: "Light"
  - coordinates:
      wdth: 87.5
      wght: 300
  - familyName: "Firjar SemiCondensed"
    styleName: "Regular"
  - coordinates:
      wdth: 87.5
      wght: 400
  - familyName: "Firjar SemiCondensed"
    styleName: "SemiBold"
  - coordinates:
      wdth: 87.5
      wght: 600
  - familyName: "Firjar SemiCondensed"
    styleName: "Bold"
  - coordinates:
      wdth: 87.5
      wght: 700
  - familyName: "Firjar SemiCondensed"
    styleName: "ExtraBold"
  - coordinates:
      wdth: 87.5
      wght: 800
  - familyName: "Firjar SemiCondensed"
    styleName: "Black"
  - coordinates:
      wdth: 87.5
      wght: 900
  - familyName: "Firjar"
    styleName: "Thin"
  - coordinates:
      wdth: 100
      wght: 100
  - familyName: "Firjar"
    styleName: "ExtraLight"
  - coordinates:
      wdth: 100
      wght: 200
  - familyName: "Firjar"
    styleName: "Light"
  - coordinates:
      wdth: 100
      wght: 300
  - familyName: "Firjar"
    styleName: "Regular"
  - coordinates:
      wdth: 100
      wght: 400
  - familyName: "Firjar"
    styleName: "SemiBold"
  - coordinates:
      wdth: 100
      wght: 600
  - familyName: "Firjar"
    styleName: "Bold"
  - coordinates:
      wdth: 100
      wght: 700
  - familyName: "Firjar"
    styleName: "ExtarBold"
  - coordinates:
      wdth: 100
      wght: 800
  - familyName: "Firjar"
    styleName: "Black"
  - coordinates:
      wdth: 100
      wght: 900
  - familyName: "Firjar SemiExpanded"
    styleName: "Thin"
  - coordinates:
      wdth: 112.5
      wght: 100
  - familyName: "Firjar SemiExpanded"
    styleName: "ExtraLight"
  - coordinates:
      wdth: 112.5
      wght: 200
  - familyName: "Firjar SemiExpanded"
    styleName: "Light"
  - coordinates:
      wdth: 112.5
      wght: 300
  - familyName: "Firjar SemiExpanded"
    styleName: "Regular"
  - coordinates:
      wdth: 112.5
      wght: 400
  - familyName: "Firjar SemiExpanded"
    styleName: "SemiBold"
  - coordinates:
      wdth: 112.5
      wght: 600
  - familyName: "Firjar SemiExpanded"
    styleName: "Bold"
  - coordinates:
      wdth: 112.5
      wght: 700
  - familyName: "Firjar SemiExpanded"
    styleName: "ExtarBold"
  - coordinates:
      wdth: 112.5
      wght: 800
  - familyName: "Firjar SemiExpanded"
    styleName: "Black"
  - coordinates:
      wdth: 112.5
      wght: 900
  - familyName: "Firjar Expanded"
    styleName: "Thin"
  - coordinates:
      wdth: 125
      wght: 100
  - familyName: "Firjar Expanded"
    styleName: "ExtraLight"
  - coordinates:
      wdth: 125
      wght: 200
  - familyName: "Firjar Expanded"
    styleName: "Light"
  - coordinates:
      wdth: 125
      wght: 300
  - familyName: "Firjar Expanded"
    styleName: "Regular"
  - coordinates:
      wdth: 125
      wght: 400
  - familyName: "Firjar Expanded"
    styleName: "SemiBold"
  - coordinates:
      wdth: 125
      wght: 600
  - familyName: "Firjar Expanded"
    styleName: "Bold"
  - coordinates:
      wdth: 125
      wght: 700
  - familyName: "Firjar Expanded"
    styleName: "ExtraBold"
  - coordinates:
      wdth: 125
      wght: 800
  - familyName: "Firjar Expanded"
    styleName: "Black"
  - coordinates:
      wdth: 125
      wght: 900